# Generated by Django 5.0.1 on 2024-01-24 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=10)),
                ('carga_maxima', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=10)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to='gestionCarga.camion')),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='gestionCarga.carga')),
            ],
        ),
        migrations.CreateModel(
            name='Bidon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('densidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidones', to='gestionCarga.carga')),
            ],
        ),
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_por_caja', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cantidad', models.IntegerField()),
                ('peso_estructura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packings', to='gestionCarga.carga')),
            ],
        ),
    ]
