# Generated by Django 5.0.1 on 2024-01-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCarga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='estado',
            field=models.CharField(max_length=50),
        ),
    ]
