# Generated by Django 5.0.1 on 2024-01-25 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCarga', '0002_alter_camion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='camion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to='gestionCarga.camion'),
        ),
    ]
